### ISSUE TITLE
Variable highligting does not apply correct tags

### ISSUE THREAD

**Issue by marstamm** [nikku/lezer-feel#10]
__Describe the Bug__

The VariableName tag is not applied correctly:

https://github.com/nikku/lezer-feel/blob/master/src/highlight.js#L24

This is because VariableName is not the bottom-most Tree node. It should be `VariableName/Identifier` or `VariableName/...` instead.

__Steps to Reproduce__

1. open the [feel playground](https://nikku.github.io/feel-playground/?e=for%0A++fruit+in+%5B+%22apple%22%2C+%22bananas%22+%5D%2C+vegetable+in+vegetables%0Areturn%0A++%7B+ingredients%3A+%5B+fruit%2C+vegetable+%5D+%7D&c=%7B%0A++%22vegetables%22%3A+%5B+%22garlic%22%2C+%22tomato%22+%5D%2C%0A++%22Mike%27s+age%22%3A+35%0A%7D&t=expression)
2. items like `fruit`, `vegetable` or `ingredients` are not highelighted

__Expected Behavior__

Variables have an applied Tag

__Environment__

- Host (Browser/Node version), if applicable: Chrome
- OS: Win 10
- Library version: 0.13.1

**Comment by marstamm** [comment]
Happy to contribute an PR for this one when I get around to it

**Comment by nikku** [comment]
This is indeed an issue and combines nicely with us not properly nesting definitions (`t.local` vs. `t.definition`) as [expected by codemirror](https://github.com/codemirror/language/blob/main/src/highlight.ts#L191).

Should look much better now (if you like colors!):

![image](https://user-images.githubusercontent.com/58601/189498537-95689149-94aa-4f43-91ed-86300d3464bc.png)

**Comment by nikku** [comment]
See also [playground reference](https://nikku.github.io/feel-playground/?e=for%0A++fruit+in+%5B+%22apple%22%2C+%22bananas%22+%5D%2C+%0A++vegetable+in+vegetables%0Areturn%0A++%7B+%0A++++%22ASD%22%3A+1%2C+%0A++++ingredients%3A+%5B+fruit%2C+vegetable+%5D%0A++%7D%0A%0A%5B+1+..+3%5D%0A%0Aevery+a+in+b+satisfies+a+%3E+100%0A%0A%7B+%0A++x%27122%3A+function+%28a%3A+list%3Ca.b.c.d%3E%2C+b%29+a+%2B+1%2C%0A++y%3A+a.b.c%2C%0A++z%3A+%5B12%5D.casdas%2C%0A++f%3A+x%27122%28y%2C+z%29%0A%7D%0A%0Adate+and+time%28%29%0A%0A%40%22100%3A100%3A100%22&c=%7B%0A++%22vegetables%22%3A+%5B+%22garlic%22%2C+%22tomato%22+%5D%2C%0A++%22Mike%27s+age%22%3A+35%0A%7D&t=expression)
