### ISSUE TITLE
Export `tokens` utilities for subclassing

### ISSUE THREAD

**Issue by marstamm** [nikku/lezer-feel#17]
__Is your feature request related to a problem? Please describe__

In my application, data stored is in another format than `{name: value}`, as I need to keep track of metadata like variable types and annotations.
Currently, I have to strip this info from the variables before parsing. It would be great if we could keep this info.

__Describe the solution you'd like__

Export [Variables](https://github.com/nikku/lezer-feel/blob/master/src/tokens.js#L429) and related utility functions. This way, I can subclass `Variables` and can create a custom ContextTracker without too much code duplication

__Describe alternatives you've considered__

- A fork of the repository that works with my data format

__Additional context__

**Comment by nikku** [comment]
Sounds like a fine thing.

We just need to be sure to integration test that utility (API wise) so it does not unintentionally break.

**Comment by nikku** [comment]
This will be addressed via https://github.com/nikku/lezer-feel/pull/18 through a custom variable context.
