### ISSUE TITLE
Support scope-provided names

### ISSUE THREAD

**Issue by barmac** [nikku/lezer-feel#3]
__Is your feature request related to a problem? Please describe__

In FEEL, the scope can provide names which do not comply with the `VariableName` in the current lezer grammar. Thus, we are not able to tell whether

```
Maciej + Nico
```

is two variables "Maciej" and "Nico" as arguments of addition "+", or a variable of name "Maciej + Nico" and certain value.

__Describe the solution you'd like__

If we want to parse correctly FEEL expressions like the one above, we may need to provide an API to allow passing the variables:

```
const parser = new LezerFEELParser({ variables });

parser.parse("Maciej + Nico");
```

 I believe we could handle such variables via an [`ExternalTokenizer`](https://lezer.codemirror.net/docs/ref/#lr.ExternalTokenizer). The lezer-feel module could provide a placeholder to be replaced via [`parser.configure`](https://lezer.codemirror.net/docs/ref/#lr.LRParser.configure) call.

Implementation sketch how it could work:

```javascript
function LezerFEELParser({ variables = [] }) {
  const externalTokenizer = new VariablesExternalTokenizer(variables);

  return BaseParser.configure({ tokenizers: [ { from: SOME_BASE, to: externalTokenizer } ] });
}
```  

__Describe alternatives you've considered__

Do nothing.

__Additional context__

See how Drools does it: https://github.com/kiegroup/drools/blob/acaf6a03837ac814265c3846f274d20b3338bc12/kie-dmn/kie-dmn-feel-gwt/src/main/java/org/kie/dmn/feel/parser/feel11/FEELParser.java#L129

**Comment by nikku** [comment]
Support for names with spaces ships with [`v0.7.0`](https://github.com/nikku/lezer-feel/blob/master/CHANGELOG.md#070).

**Comment by nikku** [comment]
Support for full contextual parsing ships with [`v0.8.0`](https://github.com/nikku/lezer-feel/blob/master/CHANGELOG.md#080):

```
import {
  parser,
  trackVariables
} from 'lezer-feel';

const contextTracker = trackVariables({
  'Maciej + Nico': {
    'if foo then bar': 100
  }
});

const contextualParser = parser.configure({
  contextTracker
});

// recognizes PathExpression<Maciej + Nico, if foo then bar>
contextualParser.parse('Maciej + Nico.if foo then bar');
```
