### ISSUE TITLE
Support for camunda extension "Escape variable names"?

### ISSUE THREAD

**Issue by makepanic** [nikku/lezer-feel#36]
### Is your feature request related to a problem? Please describe

Hi,
thanks for maintaining this great grammar for feel.
I'm wondering if it should also support escaped variables via backticks as defined in the feel guides: https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-variables/#escape-variable-names

I know it's marked as camunda extension but should the tokenizer also detect these as `VariableName`? 
Right now it just errors. This also happens in the camunda modeler.

### Describe the solution you'd like

```
`first name`

`tracking-id`

order.`total price`
```

should output VariableName tokens without errors.

### Describe alternatives you've considered

Fork this library and add support for the camunda extension which might not be intended to be included in the base grammar.

### Additional context

![20240730-160811](https://github.com/user-attachments/assets/bf7aa2a9-ef2b-456f-bc62-5bdaf7cf33fe)

**Comment by nikku** [comment]
Thanks for the issue. This repository is not the right place for such an extension. But we actively discuss a `@camunda` fork, allowing us to implement Camunda-specific quirks there.

**Comment by nikku** [comment]
What we could do, of course, is to implement this as a [grammar dialect](https://lezer.codemirror.net/docs/guide/#dialects), i.e. `camunda`.
